---
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
sort-direction: ascending

categories:
  - title: '🚨 Breaking changes'
    labels:
      - 'breaking-change'
  - title: '✨ New features'
    labels:
      - 'new-feature'
  - title: '🐛 Bug fixes'
    labels:
      - 'bugfix'
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
      - 'refactor'
      - 'performance'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'ci'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '⬆️ Dependency updates'
    collapse-after: 2
    labels:
      - 'dependencies'
  - type: "version-resolver"
    semver-increment: "major"
    when:
      labels:
        - "major"
        - "breaking-change"
  
  - type: "version-resolver"
    semver-increment: "minor"
    when:
      labels:
        - "minor"
        - "new-feature"

  - type: "version-resolver"
    semver-increment: "patch"
    when:
      labels:
        - "patch"
        - "new-feature"
        - 'bugfix'
        - 'chore'
        - 'ci'
        - 'dependencies'
        - 'documentation'
        - 'enhancement'
        - 'performance'
        - 'refactor'

autolabeler:
  - label: "maintenance"
    files:
      - "*.md"
      - ".github/*"
      - ".ruff.toml"
      - ".pre-commit-config.yaml"
      - "pyproject.toml"
      
  - label: "bugfix"
    title:
      - "/fix/i"
  - label: "code quality"
    title:
      - "lint"
  - label: "development tools"
    files:
      - ".devcontainer/*"
      - ".devcontainer.json"
      - "Makefile"
      - "setup.cfg"
      - "pyproject.toml"
      
template: |
  <!--
  ### Checklist for release
  - Run make bump - select proper variant in Makefile
  - Review the draft below and update if needed
  -->

  ## Notable Changes

  $CHANGES
